### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by AdhamAmaad** [Processus-Thief/HEKATOMB#11]
Traceback (most recent call last):
  File "/usr/bin/hekatomb", line 33, in <module>
    sys.exit(load_entry_point('hekatomb==1.5', 'console_scripts', 'hekatomb')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/hekatomb", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
when i run it it give me error like 

  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'

when i installed it it give me 

        ********************************************************************************
        Usage of dash-separated 'description-file' will not be supported in future
        versions. Please use the underscore name 'description_file' instead.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
        ********************************************************************************

**Comment by Processus-Thief** [comment]
Hey :) can you try to install it with pip ?
"pip3 install hekatomb"

**Comment by AdhamAmaad** [comment]
I did it with kali it works!
But with my arch it give me
Module need src

**Comment by Processus-Thief** [comment]
Arg, I didn't configure the installer for arch...

Try these commands to run the tool directly without installation : 

git clone https://github.com/Processus-Thief/HEKATOMB
cd HEKATOMB/src
python3 ./hekatomb.py

**Comment by AdhamAmaad** [comment]
It’s works)), I am glad man thanks a lot man
Keep going)

**Comment by Processus-Thief** [comment]
Perfect ! :)
